/**
 * exportPdf.js - Generate PDF from job data using html2pdf.js
 */

/**
 * Formats a date string consistently
 * @param {string} dateString - ISO or human-readable date string
 * @returns {string} - Formatted date (e.g., "Jan 08, 2026")
 */
function formatDate(dateString) {
  try {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: '2-digit'
    });
  } catch (err) {
    return dateString;
  }
}

/**
 * Generates styled HTML from job data
 * @param {Object} jobData - Job object with title, company, etc.
 * @param {string} markdown - Cleaned markdown content (without frontmatter)
 * @returns {string} - HTML string
 */
export function generateJobHTML(jobData, markdown) {
  // Simple Markdown to HTML conversion
  let html = markdown;

  // Convert headings
  html = html.replace(/^### (.*$)/gim, '<h3>$1</h3>');
  html = html.replace(/^## (.*$)/gim, '<h2>$1</h2>');
  html = html.replace(/^# (.*$)/gim, '<h1>$1</h1>');

  // Convert bold/italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Convert lists
  html = html.replace(/^\* (.+$)/gim, '<li>$1</li>');
  html = html.replace(/^- (.+$)/gim, '<li>$1</li>');

  // Wrap list items in <ul>
  html = html.replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>');

  // Convert line breaks to paragraphs
  html = html.split('\n\n').map(para => {
    if (para.startsWith('<h') || para.startsWith('<ul')) {
      return para;
    }
    return `<p>${para.replace(/\n/g, '<br>')}</p>`;
  }).join('\n');

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${jobData.title} - ${jobData.company}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      color: #333;
      background: #fff;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
      margin-top: 0;
    }
    h2 {
      color: #34495e;
      margin-top: 30px;
      border-bottom: 1px solid #e0e0e0;
      padding-bottom: 5px;
    }
    h3 {
      color: #555;
      margin-top: 20px;
    }
    ul {
      padding-left: 25px;
      margin: 10px 0;
    }
    li {
      margin: 8px 0;
    }
    .metadata {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      margin-bottom: 30px;
      font-size: 14px;
      border-left: 4px solid #3498db;
      line-height: 1.8;
      word-wrap: break-word;
      overflow-wrap: break-word;
    }
    .metadata strong {
      color: #555;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 12px;
      color: #999;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="metadata">
    <strong>Job ID:</strong> ${jobData.job_id}<br>
    <strong>Company:</strong> ${jobData.company}<br>
    <strong>Saved:</strong> ${formatDate(jobData.saved_at)}
    ${jobData.application_deadline ? ` &nbsp;&nbsp; <strong>Deadline:</strong> ${formatDate(jobData.application_deadline)}` : ''}
    ${jobData.published ? ` &nbsp;&nbsp; <strong>Published:</strong> ${formatDate(jobData.published)}` : ''}
  </div>

  <h1>${jobData.title}</h1>

  ${html}

  <div class="footer">
    Generated by JobSnap v2.0 &bull; ${formatDate(new Date().toISOString())}
  </div>
</body>
</html>
`;
}

/**
 * Strips YAML frontmatter and duplicate metadata from markdown
 * @param {string} markdown - Raw markdown with frontmatter
 * @returns {string} - Cleaned markdown
 */
export function stripMetadata(markdown) {
  let lines = markdown.split('\n');

  // Remove YAML frontmatter (between --- delimiters)
  if (lines[0] === '---') {
    const endIndex = lines.slice(1).findIndex(line => line === '---');
    if (endIndex !== -1) {
      lines = lines.slice(endIndex + 2);
    }
  }

  // Remove leading empty lines
  while (lines.length > 0 && lines[0].trim() === '') {
    lines.shift();
  }

  // Remove title heading (# Title)
  if (lines.length > 0 && lines[0].startsWith('# ')) {
    lines.shift();
  }

  // Remove leading empty lines again
  while (lines.length > 0 && lines[0].trim() === '') {
    lines.shift();
  }

  // Remove **Company:** and **Application Deadline:** lines
  while (lines.length > 0 && (lines[0].startsWith('**Company:**') || lines[0].startsWith('**Application Deadline:**') || lines[0].trim() === '')) {
    lines.shift();
  }

  return lines.join('\n').trim();
}

/**
 * Exports job as PDF using html2pdf.js
 * @param {Object} options
 * @param {Object} options.jobData - Job metadata (title, company, job_id, etc.)
 * @param {string} options.markdown - Raw markdown content
 * @param {string} options.filename - Filename without extension
 * @returns {Promise<void>}
 */
export async function exportJobAsPDF({ jobData, markdown, filename }) {
  // Load html2pdf library
  const html2pdf = window.html2pdf;
  if (!html2pdf) {
    throw new Error('html2pdf library not loaded');
  }

  // Strip metadata from markdown
  const cleanedMd = stripMetadata(markdown);

  // Generate HTML
  const html = generateJobHTML(jobData, cleanedMd);

  // Extract body content from full HTML document
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  // Get the body content and styles
  const bodyContent = doc.body.innerHTML;
  const styles = doc.querySelector('style')?.innerHTML || '';

  // Create temporary container with inline styles
  const container = document.createElement('div');
  const styleEl = document.createElement('style');
  styleEl.textContent = styles;
  container.appendChild(styleEl);

  const contentDiv = document.createElement('div');
  contentDiv.innerHTML = bodyContent;
  container.appendChild(contentDiv);

  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.style.width = '800px';
  document.body.appendChild(container);

  try {
    // Wait a bit for rendering
    await new Promise(resolve => setTimeout(resolve, 100));

    // Generate PDF with optimized settings
    const pdfFilename = filename.replace(/\.md$/, '.pdf');

    await html2pdf()
      .set({
        margin: [20, 15, 20, 15],
        filename: pdfFilename,
        image: { type: 'jpeg', quality: 0.92 },
        html2canvas: {
          scale: 1.5,
          useCORS: true,
          windowWidth: 800,
          windowHeight: container.scrollHeight
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
      })
      .from(contentDiv)
      .save();
  } catch (err) {
    console.error('PDF generation error:', err);
    throw err;
  } finally {
    // Cleanup
    document.body.removeChild(container);
  }
}
